micronaut:
  application:
    name: lab2_AmazonDynamoDBScansQueriesandIndexes
netty:
  default:
    allocator:
      max-order: 3
dynamodb:
  region: US-EAST-1
  endpoint: http://localhost:9000
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false
